### PR TITLE
Closes Issue 42 -- Consider s3 classes

### PR DESCRIPTION
**Pull request by jsonbecker**
Following the discussion on #42, this PR includes a change to using S3 method dispatch rather than a `switch` statement in both `import` and `export` by adding a new generic methods `.import` and `.export`. These changes should be entirely transparent to users, but offers flexibility for importers and exporters to be written outside of `rio` directly.

Implementation is detailed primarily in f01954f, but some highlights:

* Both import and export have their methods ordered to follow the sequence of the old `switch` statement.
* In some cases, `rio` wrapped several import or export methods in another function like `import.delim`, rather than directly use the strategy for import or export in a switch statement. When this is the case for only one possible type, these functions are changed to methods on that type. When this is the case for more than one possible type, the original function remains and is called by each class method. In the case of `import.delim`, where several class methods are still calling this function, I would recommend a change to `import_delim` to avoid confusion with the S3 methods in the future.

### CODE REVIEW

**Comment by jsonbecker** [comment]
Not sure what is causing the merge conflicts here. I think it may be the changes to the tests, but it's possible I was behind by some other set of commits. I also didn't adjust the DESCRIPTION file at all because I was uncertain of versioning rules + don't want to presume myself an author until this PR is accepted.

**Comment by leeper** [comment]
This looks good. I've pulled it in as a feature branch and will play around with it soon.

**Comment by jsonbecker** [comment]
@leeper I've been thinking about this lately and I've been wondering if:
https://github.com/leeper/rio/blob/s3classes/R/utils.R#L62 should be changed to `warning()` instead of `stop()`. One goal of the S3 refactor is making it easier to extend `rio` to new data types that don't make sense for the core package, but this function would actually cause an error with anything not on the recognized list. Given the default class method already has an error if no other function is dispatched to, I don't think we need the guard in `get_type`.

**Comment by leeper** [comment]
Correct. It should just return the format, even if it's not a "recognized" type.

**Comment by leeper** [comment]
I've merged this in and added the extensibility mechanism as discussed.

**Pull request merged**
