### PR TITLE
Add support to `import_list()` for SQL dump. Other changes noted in `NEWS.md`

### PR DESCRIPTION
**Pull request by ryapric**
I've added support for importing SQL dump scripts (SQLite only, as tested, but the query builder I wrote is easily extensible to reduce other RDBMS to SQL standard statements that SQLite can handle). I have had SQL scripts sent to me at my place of work in the past, but even outside of that limited example, I figure users can use this for sharing DB data, when regular DB connections aren't the best immediate option.

One scenario might be that an R developer writes some analysis script that runs `import("dump.sql")` at the start, where `dump.sql` is whatever that person's SQL developer peers can pass a SQL dump script as input on the command line. Then there's some transformation/analysis work that happens as a result of that R script, but that doesn't require the SQL developers to know R, or fight with config issues when DB connections from R aren't working.

I'm open to dropping some of the other changes, but I noticed them while I was working, and thought that the `install_formats()` especially could be more robust (as I needed to either add `RSQLite` to one, or both of the `DESCRIPTION`, and the vector in the function call).

Thanks for this package, and please let me know if you have comments or concerns on this PR!

### CODE REVIEW

**Comment by ryapric** [comment]
Just FYI, it looks like Travis failed above because of some network issue on their side; it couldn't read some remote files in examples & tests (none of mine).

**Comment by ryapric** [comment]
Closing while I close some loopholes, and add PostgreSQL support, as well.

**Comment by chainsawriot** [comment]
Do you aware of this package?

https://github.com/leeper/rio.db

**Comment by leeper** [comment]
There are some good changes, here so maybe break apart into two PRs:

1. the miscellaneous fixes you're introducing
2. database support. @chainsawriot is right that there's a rio.db mockup package but it might be better long-term to wrap that functionality into the main package (using Suggests).

**Comment by ryapric** [comment]
Thanks for the replies! Yes, I did see `rio.db` pointed out as I checked over the `README` here, but from what I saw in the source code, it's reading from connections to tables that *already exist* in a SQLite database. My intention is to add support for `import()`-ing the tables that would be generated via SQL queries themselves. I think those are separate aims, as I wouldn't consider the latter to be adding "database support/functionality/interface", per se.

But thank you for your suggestion, I'll submit the various changes as separate PRs, then!

**Pull request closed without merging**
