### PR TITLE
Long url to determine shortened URLs' file formats

### PR DESCRIPTION
**Pull request by christophergandrud**
`import` uses the [longurl package](https://github.com/hrbrmstr/longurl) to expand shortened URLs so that their file formats can be easily determined.

Here is an example:

```{S}
polity <- rio::import('http://bit.ly/1g5pJmX')
```

### CODE REVIEW

**Comment by leeper** [comment]
Can we make an option to regulate this? I'm slightly concerned that if the API goes down, the package will be unable to download these URLs at all (whereas the current setup should work in many cases).

**Comment by christophergandrud** [comment]
Good point. I just added an `expandurl` argument to `import` that allows the user to ignore this. I've set it to `TRUE` by default as it doesn't make a lot of sense otherwise (might as well just set the file format manually if you're going to specify another argument).

**Comment by leeper** [comment]
Excellent. I think that's the right approach. Can you squash all of this down to one commit?

**Comment by christophergandrud** [comment]
Sure (sorry for the additional merge commit, but all of the changes are in 9541d24)

**Comment by leeper** [comment]
Cool. It's merged now.

**Comment by christophergandrud** [comment]
:+1:

**Pull request closed without merging**
